= {title}
:title:       Admonition Paragraphs
:description: http://asciidoc.org/userguide.html#X28
:doctitle:    Text behavior - {title}
include::attributes.asciidoc[]
:navinfo2:
:icons!:
:iconsfont!:
:jumbotron:
:footer!:
:stylesheet: admonition-text.default.css

include::admonition-samples.asciidoc[]

== Learn More

.Behind the scene
************************************************
Have a look in the LESS source file `less/asciidoc-bootstrap.less`, you should have at least this line activated 
footnote:[{rawbaseurl}/less/asciidoc/admonition-text.less] :
----
@import "asciidoc/admonition-text.less";
----

And this other line deactivated (if you don't want to use Icons Font feature) :
----
@import "asciidoc/admonition-iconsfont.less";
----
************************************************

If you want to modify the default render, either change the `less/asciidoc/admonition-text.less` source file,
and rebuild the `asciidoc-bootstrap.css` file,  
or copy the CSS rules in a new CSS file (free name), and build your page ( AsciiDoc ) with attribute `stylesheet`. 

IMPORTANT: *Your custom stylesheet MUST be located in the `{stylesdir}`.*

E.g:

----
$ asciidoc.py 
  -b bootstrap
  -a linkcss
  -a stylesdir=./stylesheets
  -a scriptsdir=./javascripts
  -a theme=flatly
  -a stylesheet=admonition-text.css
  -a navbar=fixed
  -a totop
  {docfile}
----

[source,css] 
.Content of `admonition-text.css`
----
include::../stylesheets/admonition-text.css[]
----

See results in live with :

* standard  link:admonition-text-custom.html5.html[AsciiDoc] html5 backend.
* Bootstrap link:admonition-text-custom.default.html[default] theme.
* Bootswatch link:admonition-text-custom.flatly.html[flatly] theme.
* Bootstrap link:admonition-text-custom.readable.html[readable] theme.
