
== Admonition NOTE block

====
----
NOTE: This is an example note.

[NOTE]
Alternatively, you can specify the paragraph admonition style explicitly using an AttributeList element.
----
====
Renders:

NOTE: This is an example note.

[NOTE]
Alternatively, you can specify the paragraph admonition style explicitly using an AttributeList element.

== Admonition IMPORTANT block

====
----
IMPORTANT: This is another example more important.
----
====
Renders:

IMPORTANT: This is another example more important.

== Admonition CAUTION block

====
----
CAUTION: This is another example important but less.
----
====
Renders:

CAUTION: This is another example important but less.

== Admonition WARNING block

====
----
WARNING: This is a warning example.
----
====
Renders:

WARNING: This is a warning example.

== Admonition NOTE custom icon block

====
----
[icon="./images/icons/example.png"]
NOTE: What lovely war.
----
====
Renders:

[icon="./images/icons/example.png"]
NOTE: What lovely war.

== Admonition TIP block

====
----
[TIP]
.A TIP admonition block
=====================================================================
Qui in magna commodo, est labitur dolorum an. Est ne magna primis
adolescens.

. Fusce euismod commodo velit.
. Vivamus fringilla mi eu lacus.
  .. Fusce euismod commodo velit.
  .. Vivamus fringilla mi eu lacus.
. Donec eget arcu bibendum
  nunc consequat lobortis.
=====================================================================
----
====
Renders:

[TIP]
.A TIP admonition block
=====================================================================
Qui in magna commodo, est labitur dolorum an. Est ne magna primis
adolescens.

. Fusce euismod commodo velit.
. Vivamus fringilla mi eu lacus.
  .. Fusce euismod commodo velit.
  .. Vivamus fringilla mi eu lacus.
. Donec eget arcu bibendum
  nunc consequat lobortis.
=====================================================================
