= {title}
:title:       Delimited Blocks
:description: http://www.methods.co.nz/asciidoc/userguide.html#X104
include::attributes.asciidoc[]
:navinfo2:

ifdef::basebackend-bootstrap[]

//////////////////////////
   Bootstrap 2 syntax
//////////////////////////
ifeval::["{bsver}"=="2"]
:well-small: well-small
:well-large: well-large
endif::[]

//////////////////////////
   Bootstrap 3 syntax
//////////////////////////
ifeval::["{bsver}"=="3"]
:well-small: well-sm
:well-large: well-lg
endif::[]

endif::[]


== Sidebar blocks

[role="lead"]
A sidebar is a short piece of text presented outside the narrative flow of the main text. 
The sidebar is normally presented inside a bordered box to set it apart from the main text.

====
----
.An Example Sidebar
************************************************
Any AsciiDoc SectionBody element (apart from
SidebarBlocks) can be placed inside a sidebar.
************************************************
----
====
Renders:

.An Example Sidebar
************************************************
Any AsciiDoc SectionBody element (apart from
SidebarBlocks) can be placed inside a sidebar.
************************************************

You may also used the attribute `role` to control padding and rounded corners.

With `role` set to value *well-small* [label label-info]#Bootstrap 2#, or *well-sm* [label label-info]#Bootstrap 3#
====
----
.An Example Sidebar
[role="well-small"]
****
Any AsciiDoc SectionBody element (apart from
SidebarBlocks) can be placed inside a sidebar.
****
----
====
Renders:

.An Example Sidebar
[role="{well-small}"]
****
Any AsciiDoc SectionBody element (apart from
SidebarBlocks) can be placed inside a sidebar.
****

With `role` set to value *well-large* [label label-info]#Bootstrap 2#, or *well-lg* [label label-info]#Bootstrap 3#
====
----
.An Example Sidebar
[role="well-large"]
****
Any AsciiDoc SectionBody element (apart from
SidebarBlocks) can be placed inside a sidebar.
****
----
====
Renders:

.An Example Sidebar
[role="{well-large}"]
****
Any AsciiDoc SectionBody element (apart from
SidebarBlocks) can be placed inside a sidebar.
****

== About _this document_
link:howto.html#how_to_build_internal_pages[How to] build the source code
footnote:[https://raw.github.com/llaville/asciidoc-bootstrap-backend/master/docs/delimited-blocks.asciidoc].
