= {title}
:title:       Delimited Blocks
:description: http://asciidoc.org/userguide.html#X104
include::attributes.asciidoc[]
:navinfo2:
:icons!:
:iconsfont:   font-awesome
:jumbotron:
:footer!:


== Sidebar Blocks

[role="lead"]
A sidebar is a short piece of text presented outside the narrative flow of the main text.
The sidebar is normally presented inside a bordered box to set it apart from the main text.

====
----
.An Example Sidebar
************************************************
Any AsciiDoc SectionBody element (apart from
SidebarBlocks) can be placed inside a sidebar.
************************************************
----
====
Renders:

.An Example Sidebar
************************************************
Any AsciiDoc SectionBody element (apart from
SidebarBlocks) can be placed inside a sidebar.
************************************************

You may also used the attribute `role` to control padding and rounded corners.

With *well-sm* role:
====
----
.An Example Sidebar
[role="well-sm"]
****
Any AsciiDoc SectionBody element (apart from
SidebarBlocks) can be placed inside a sidebar.
****
----
====
Renders:

.An Example Sidebar
[role="well-sm"]
****
Any AsciiDoc SectionBody element (apart from
SidebarBlocks) can be placed inside a sidebar.
****

With *well-lg* role:
====
----
.An Example Sidebar
[role="well-lg"]
****
Any AsciiDoc SectionBody element (apart from
SidebarBlocks) can be placed inside a sidebar.
****
----
====
Renders:

.An Example Sidebar
[role="well-lg"]
****
Any AsciiDoc SectionBody element (apart from
SidebarBlocks) can be placed inside a sidebar.
****

== Open Blocks

[role="lead"]
Open blocks are special: they are used to generate document abstracts,
book part introductions and more.

WARNING: Previous version 3, used it to simulate multi columns. Version 4 dropped this behavior.
Don't be afraid, this feature is still possible using the standard Bootstrap classes like `.col-md-*` and so on.

First open block structure is used to implement the Bootstrap Panel Component.

[role="col-md-4"]
.Panel with primary contextual state class
====
[panel,primary]
.Panel title
--
Panel content
--
====

[role="col-md-4"]
.Panel with success contextual state class
====
[panel,success]
.Panel title
--
Panel content
--
====

[role="col-md-4"]
.Panel with warning contextual state class
====
[panel,warning]
.Panel title
--
Panel content
--
====

link:panels.default.html[Learn more] how AsciiDoc-Bootstrap backend implements this feature.

footnote:[https://raw.github.com/llaville/asciidoc-bootstrap-backend/master/docs/delimited-blocks.asciidoc].
