= Document Structure
:doctitle:    Document Structure
:description: http://asciidoc.org/userguide.html#_document_structure
include::attributes.asciidoc[]
:navinfo2:


== Backend Attributes

[cols="1e,5a",options="header",role="table table-bordered"]
|====================================================================
|Name |Description

| navinfo, navinfo1, navinfo2 |
These three attributes control which navigation information
files will be included in the output file:

navinfo:: Include `<filename>-navinfo.html`
navinfo1:: Include `navinfo.html`
navinfo2:: Include `navinfo.html` and `<filename>-navinfo.html`

Where `<filename>` is the file name (without extension) of the AsciiDoc
input file.

The following example will include a `navinfo.html` and `mydoc-navinfo.html`
navinfo files in the HTML output file:

  $ asciidoc -b bootstrap -a navinfo2 mydoc.txt

| jumboinfo, jumboinfo1, jumboinfo2 |
These three attributes control which jumbotron information
files will be included in the output file:

jumboinfo:: Include `<filename>-jumboinfo.html`
jumboinfo1:: Include `jumboinfo.html`
jumboinfo2:: Include `jumboinfo.html` and `<filename>-jumboinfo.html`

Where `<filename>` is the file name (without extension) of the AsciiDoc
input file.

The following example will include a `jumboinfo.html` and `mydoc-jumboinfo.html`
jumboinfo files in the HTML output file:

  $ asciidoc -b bootstrap -a jumboinfo2 mydoc.txt

| footer |
This attribute control which footer informations
will be included in the output file:

If not defined, then it will be the default footer with
the version and last updated informations.

footer:: Include `footer.html`

The following example will include the `footer.html` file
in the HTML output file:

  $ asciidoc -b bootstrap -a footer mydoc.txt

| totop |
This attribute control which _back to top_ system you want to include in the output file.

when attribute unset:: Include a _Back to top_ standard html href link
when attribute set::   Used the http://mattvarone.com/web-design/uitotop-jquery-plugin/[UItoTop jQuery plugin].

The following example will include a dynamic clickable area
in the HTML output file:

  $ asciidoc -b bootstrap -a totop mydoc.txt

| themeswitcher |
This attribute allow to used a Bootstrap Theme Switcher with the https://github.com/jguadagno/bootstrapThemeSwitcher[jQuery plugin].

| brandver |
This attribute control whether you want to include a dynamic versions list in the output file.
A `versions.html` file must exists.

The following example will not include a static versions list, identified by the navinfo.html,
in the HTML output file (default behavior):

  $ asciidoc -b bootstrap -a brandver! mydoc.txt

|====================================================================

== Examples

=== Jumbotron

Learn more at the link:jumbotron.html[Jumbotron Bootstrap Component] page.

=== Navigation bar

.Example of left navigation menu: _document-structure-navinfo.html_
[source,html]
----
include::document-structure-navinfo.html[]
----

.Example of right navigation menu: _navinfo.html_
[source,html]
----
include::navinfo.html[]
----

=== Footer

.Example of footer file: _footer.html_
[source,html]
----
include::footer.html[]
----
