= {title}
:title:       Document Structure
:description: http://www.methods.co.nz/asciidoc/userguide.html#_document_structure
include::attributes.asciidoc[]
:navinfo2:


== Backend Attributes

[cols="1e,5a",options="header",role="table table-bordered"]
|====================================================================
|Name |Description

| navinfo, navinfo1, navinfo2 |
These three attributes control which navigation information
files will be included in the output file:

navinfo:: Include `<filename>-navinfo.html`
navinfo1:: Include `navinfo.html`
navinfo2:: Include `navinfo.html` and `<filename>-navinfo.html`

Where `<filename>` is the file name (without extension) of the AsciiDoc
input file. The following example will include the
`mydoc-navinfo.html` navinfo file in the HTML output file:

  $ asciidoc -a navinfo -b bootstrap mydoc.txt

This next example will include `navinfo.html` and `mydoc-navinfo.html`
navinfo files in the HTML output file:

  $ asciidoc -a navinfo2 -b bootstrap mydoc.txt

| footer |
This attribute control which footer informations
will be included in the output file:

If not defined, then it will be the default footer with a link back to top,
the version and last updated informations.

footer:: Include `footer.html`

The following example will include the `footer.html` file
in the HTML output file:

  $ asciidoc -a footer -b bootstrap mydoc.txt

|====================================================================

.Example of left navigation menu: _document-structure-navinfo.html_
[source,html]
----
include::document-structure-navinfo.html[]
----

.Example of right navigation menu: _navinfo.html_
[source,html]
----
include::navinfo.html[]
----

.Example of footer file: _footer.html_
[source,html]
----
include::footer.html[]
----
