= {title}
:title:       Paragraphs
:description: http://asciidoc.org/userguide.html#_paragraphs
include::attributes.asciidoc[]
:navinfo2:
:icons!:
:iconsfont:   font-awesome
:jumbotron:


== Admonition paragraphs

[role="lead"]
'TIP', 'NOTE', 'IMPORTANT', 'WARNING' and 'CAUTION' admonishment
paragraph styles are generated by placing `NOTE:`, `TIP:`,
`IMPORTANT:`, `WARNING:` or `CAUTION:` as the first word of the
paragraph.

Since version 1.2.0, admonitionblock used _alert-block_ Twitter Bootstrap styles.
With support of icons font, it's now time to change the behavior and default styles.

To compare three render categories, we will use the same file source
footnote:[{rawbaseurl}/docs/admonition-samples.asciidoc].

=== Using text captions

By default the AsciiDoc HTML backends generate text captions instead of admonition icon image links.

Want to link:admonition-text.cerulean.html[see] what it look like without images or icons font symbols.

=== Using images

By default the AsciiDoc HTML backends generate text captions instead of admonition icon image links.
To generate links to icon images define the `icons` attribute,
for example using the +-a icons+ command-line option.

As AsciiDoc, this backend will have the same default behavior.

Want to link:admonition-images.cerulean.html[see] what it look like.

=== Using icons font

Since version 3.1.0, admonitionblock may optionally used icons font to draw icons.
To generate links to icons font symbols define the `iconsfont` attribute.

Remember that you can use any of icons font support by the backend.

* http://glyphicons.com/[Glyphicons] - use +-a iconsfont=glyphicon+
* http://fontawesome.io[Font-Awesome] - use +-a iconsfont=font-awesome+
* http://ionicons.com/[Ionicons] - use +-a iconsfont=ionicons+

Want to link:admonition-iconsfont.cerulean.html[see] what it look like with Font-Awesome.

footnote:[{rawbaseurl}/docs/paragraphs.asciidoc].
