= {title}
:title:       Paragraphs
:description: http://www.methods.co.nz/asciidoc/userguide.html#_paragraphs
include::attributes.asciidoc[]
:navinfo2:


== Admonition paragraphs

[role="lead"]
'TIP', 'NOTE', 'IMPORTANT', 'WARNING' and 'CAUTION' admonishment
paragraph styles are generated by placing `NOTE:`, `TIP:`,
`IMPORTANT:`, `WARNING:` or `CAUTION:` as the first word of the
paragraph.

====
----
NOTE: This is an example note.

[NOTE]
Alternatively, you can specify the paragraph admonition style explicitly using an AttributeList element.
----
====
Renders:

NOTE: This is an example note.

[NOTE]
Alternatively, you can specify the paragraph admonition style explicitly using an AttributeList element.

====
----
IMPORTANT: This is another example more important.
----
====
Renders:

IMPORTANT: This is another example more important.

====
----
CAUTION: This is another example important but less.
----
====
Renders:

CAUTION: This is another example important but less.

====
----
WARNING: This is a warning example.
----
====
Renders:

WARNING: This is a warning example.

====
----
[icon="./images/icons/example.png"]
NOTE: What lovely war.
----
====
Renders:

[icon="./images/icons/example.png"]
NOTE: What lovely war.

====
----
[NOTE]
.A NOTE admonition block
=====================================================================
Qui in magna commodo, est labitur dolorum an. Est ne magna primis
adolescens.

. Fusce euismod commodo velit.
. Vivamus fringilla mi eu lacus.
  .. Fusce euismod commodo velit.
  .. Vivamus fringilla mi eu lacus.
. Donec eget arcu bibendum
  nunc consequat lobortis.
=====================================================================
----
====
Renders:

[NOTE]
.A NOTE admonition block
=====================================================================
Qui in magna commodo, est labitur dolorum an. Est ne magna primis
adolescens.

. Fusce euismod commodo velit.
. Vivamus fringilla mi eu lacus.
  .. Fusce euismod commodo velit.
  .. Vivamus fringilla mi eu lacus.
. Donec eget arcu bibendum
  nunc consequat lobortis.
=====================================================================
